<?php

/**
 * @file
 * Module functions.
 */

/**
 * Implements hook_form_alter().
 */
function form_alter_info_form_alter(&$form, &$form_state, $form_id) {
  if (user_access('access devel information')) {
    $enabled = variable_get('form_alter_info_enabled', FALSE);

    if ($enabled) {
      $info = array();
      $info['form_id'] = $form_id;
      $info['form'] = $form;

      // Collect alter hooks names to be called.
      $hooks = array('form');
      if (isset($form_state['build_info']['base_form_id'])) {
        $hooks[] = 'form_' . $form_state['build_info']['base_form_id'];
      }
      $hooks[] = 'form_' . $form_id;

      // Collect existing implementations for those hooks.
      $functions = array();
      foreach ($hooks as $base) {
        $hook = $base . '_alter';

        $functions[$hook] = array();

        $modules = module_implements($hook);
        foreach ($modules as $module) {
          $functions[$hook][] = $module . '_' . $hook;
        }
      }
      $info['hooks_called'] = $functions;

      // Call all the hooks to check which ones modify the form.
      foreach ($functions as $hook => $hook_functions) {
        foreach ($hook_functions as $function) {
          if (function_exists($function)) {
            // Avoid infinite recursion.
            if ($function != 'form_alter_info_form_alter') {
              $form_copy = $form;
              $form_state_copy = $form_state;

              // Call the altering function.
              $function($form_copy, $form_state_copy, $form_id);

              // Check for differences.
              $diff = drupal_array_diff_assoc_recursive($form_copy, $form);

              // Collect info about hooks altering the form.
              if (!empty($diff)) {
                $info['hooks_altering'][$hook][$function] = array(
                  'array_diff' => $diff,
                );
              }
            }
          }
        }
      }

      dpm($info, t('Form info for @form_id', array('@form_id' => $form_id)), 'info');
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function form_alter_info_form_devel_admin_settings_alter(&$form, &$form_state) {
  $form['form_alter_info'] = array(
    '#type' => 'fieldset',
    '#title' => t('Form alter info'),
    '#collapsible' => FALSE,
  );

  $form['form_alter_info']['form_alter_info_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Display form alter info'),
    '#default_value' => variable_get('form_alter_info_enabled', FALSE),
    '#description' => t('For each form displayed on the page this feature displays info about all hooks that are been called and the ones altering the form.'),
  );
}

/**
 * Recursively computes the difference of arrays with additional index check.
 *
 * This is a version of array_diff_assoc() that supports multidimensional
 * arrays.
 *
 * Copied from Drupal 7.
 *
 * @param array $array1
 *   The array to compare from.
 * @param array $array2
 *   The array to compare to.
 *
 * @return array
 *   Returns an array containing all the values from array1 that are not present
 *   in array2.
 */
function drupal_array_diff_assoc_recursive($array1, $array2) {
  $difference = array();

  foreach ($array1 as $key => $value) {
    if (is_array($value)) {
      if (!array_key_exists($key, $array2) || !is_array($array2[$key])) {
        $difference[$key] = $value;
      }
      else {
        $new_diff = drupal_array_diff_assoc_recursive($value, $array2[$key]);
        if (!empty($new_diff)) {
          $difference[$key] = $new_diff;
        }
      }
    }
    elseif (!array_key_exists($key, $array2) || $array2[$key] !== $value) {
      $difference[$key] = $value;
    }
  }

  return $difference;
}
